-- =============================================
-- GRANJA DON BOSCO - ESQUEMA GENERAL
-- =============================================

-- 1. TABLA DE USUARIOS
CREATE TABLE IF NOT EXISTS usuarios (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  nombre_completo TEXT NOT NULL,
  rol TEXT NOT NULL DEFAULT 'colaborador',
  departamento TEXT,
  puede_editar BOOLEAN DEFAULT FALSE,
  puede_eliminar BOOLEAN DEFAULT FALSE,
  puede_agregar BOOLEAN DEFAULT FALSE,
  puede_inventario BOOLEAN DEFAULT FALSE,
  correo TEXT NOT NULL,
  
  foto_url TEXT,
  ultima_conexion TIMESTAMPTZ,
  creado_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABLA DE PRODUCTOS
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  category TEXT,
  stock INTEGER DEFAULT 0,
  unidad_medida TEXT DEFAULT 'Unidad',
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABLA DE TAREAS
CREATE TABLE IF NOT EXISTS tareas (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  creado_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABLA DE JORNADAS LABORALES
CREATE TABLE IF NOT EXISTS jornadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  tarea_id INTEGER REFERENCES tareas(id),
  creado_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABLA DE PEDIDOS/VENTAS
CREATE TABLE IF NOT EXISTS orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios(id),
  total DECIMAL(10,2) NOT NULL,
  metodo_pago TEXT NOT NULL DEFAULT 'efectivo',
  status TEXT NOT NULL DEFAULT 'completado',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. TABLA DE MENSAJES DE CHAT
CREATE TABLE IF NOT EXISTS mensajes_chat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
  nombre_usuario TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  rol_usuario TEXT DEFAULT 'colaborador',
  grupo_id BIGINT REFERENCES grupos_chat(id) ON DELETE SET NULL,
  creado_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. TABLA DE GRUPOS DE CHAT
CREATE TABLE IF NOT EXISTS grupos_chat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  creador_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  miembros UUID[] DEFAULT '{}',
  creado_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =============================================
-- DATOS INICIALES
-- =============================================

-- Tareas iniciales
INSERT INTO tareas (nombre, descripcion) VALUES 
  ('Ventas', 'Atención en punto de venta y despacho'),
  ('Cuidado Animal', 'Alimentación y revisión de animales'),
  ('Producción Lácteos', 'Elaboración de quesos y derivados'),
  ('Mantenimiento', 'Limpieza y reparaciones de la granja'),
  ('Administración', 'Gestión de inventarios y personal')
ON CONFLICT (id) DO NOTHING;

-- Productos de ejemplo
INSERT INTO products (name, price, category, stock) VALUES
  ('Leche Fresca (botella)', 1.25, 'LÁCTEOS', 100),
  ('Queso Fresco (libra)', 2.50, 'LÁCTEOS', 50),
  ('Queso Duro (libra)', 3.50, 'LÁCTEOS', 30),
  ('Crema Pura (botella)', 2.50, 'LÁCTEOS', 40),
  ('Requesón (libra)', 1.50, 'LÁCTEOS', 25),
  ('Pollo Entero (6 libras)', 8.00, 'PRODUCTOS DE POLLO', 20),
  ('Pechugas de Pollo (libra)', 1.60, 'PRODUCTOS DE POLLO', 30),
  ('Piernas de Pollo (libra)', 1.25, 'PRODUCTOS DE POLLO', 25),
  ('Carne de Res (libra)', 4.50, 'CARNES', 15),
  ('Carne de Cerdo (libra)', 2.50, 'CARNES', 12),
  ('Huevos (cartón de 30)', 3.50, 'OTROS ALIMENTOS', 200),
  ('Miel (botella)', 4.00, 'OTROS ALIMENTOS', 20),
  ('Gallinas Rojas vivas', 8.00, 'ANIMALES', 10),
  ('Pavos (chompipe)', 28.00, 'ANIMALES', 8),
  ('Conejos (mascotas)', 10.00, 'ANIMALES', 15),
  ('Vacuna Triple Aviar (50ml)', 15.00, 'VACUNAS Y MEDICINA', 100),
  ('Vacuna Viruela Aviar 100 dosis', 12.00, 'VACUNAS Y MEDICINA', 50),
  ('Concentrado Alianza Inicio (quintal)', 20.00, 'CONCENTRADOS', 80),
  ('Concentrado Alianza Final (quintal)', 19.50, 'CONCENTRADOS', 60)
ON CONFLICT (id) DO NOTHING;

-- =============================================
-- SEGURIDAD (RLS)
-- =============================================

ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE tareas ENABLE ROW LEVEL SECURITY;
ALTER TABLE jornadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE mensajes_chat ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos_chat ENABLE ROW LEVEL SECURITY;

-- Políticas para usuarios
CREATE POLICY "Usuarios pueden ver todos los perfiles" ON usuarios FOR SELECT TO authenticated USING (true);
CREATE POLICY "Usuarios pueden actualizar su propio perfil" ON usuarios FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Políticas para productos
CREATE POLICY "Todos pueden ver productos" ON products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins pueden insertar productos" ON products FOR INSERT TO authenticated WITH CHECK (
  (SELECT rol FROM usuarios WHERE id = auth.uid()) = 'admin'
);
CREATE POLICY "Admins pueden actualizar productos" ON products FOR UPDATE TO authenticated USING (
  (SELECT rol FROM usuarios WHERE id = auth.uid()) = 'admin'
);
CREATE POLICY "Admins pueden eliminar productos" ON products FOR DELETE TO authenticated USING (
  (SELECT rol FROM usuarios WHERE id = auth.uid()) = 'admin'
);

-- Políticas para tareas
CREATE POLICY "Todos pueden ver tareas" ON tareas FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins pueden gestionar tareas" ON tareas FOR ALL TO authenticated USING (
  (SELECT rol FROM usuarios WHERE id = auth.uid()) = 'admin'
);

-- Políticas para jornadas
CREATE POLICY "Usuarios pueden ver sus jornadas" ON jornadas FOR SELECT TO authenticated USING (auth.uid() = usuario_id);
CREATE POLICY "Usuarios pueden crear jornadas" ON jornadas FOR INSERT TO authenticated WITH CHECK (auth.uid() = usuario_id);

-- Políticas para orders
CREATE POLICY "Todos pueden ver orders" ON orders FOR SELECT TO authenticated USING (true);
CREATE POLICY "Usuarios pueden crear orders" ON orders FOR INSERT TO authenticated WITH CHECK (true);

-- Políticas para chat
CREATE POLICY "Todos pueden ver mensajes" ON mensajes_chat FOR SELECT TO authenticated USING (true);
CREATE POLICY "Usuarios pueden enviar mensajes" ON mensajes_chat FOR INSERT TO authenticated WITH CHECK (auth.uid() = usuario_id);

-- Políticas para grupos_chat
CREATE POLICY "Todos pueden ver grupos" ON grupos_chat FOR SELECT TO authenticated USING (true);
CREATE POLICY "Usuarios pueden crear grupos" ON grupos_chat FOR INSERT TO authenticated WITH CHECK (auth.uid() = creador_id);

-- =============================================
-- STORAGE (AVATARES)
-- =============================================

-- Crear bucket de avatares si no existe
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Política de acceso a avatares
CREATE POLICY "Avatares son públicos para lectura"
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

CREATE POLICY "Usuarios pueden subir avatares"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Usuarios pueden actualizar avatares"
ON storage.objects FOR UPDATE
USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

-- =============================================
-- NOTIFICACIÓN DE NUEVOS USUARIOS (Trigger)
-- =============================================

-- Función para crear perfil automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.usuarios (id, nombre_completo, correo, rol)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nombre_completo', NEW.email),
    NEW.email,
    'colaborador'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =============================================
-- FUNCIONES ÚTILES
-- =============================================

-- Actualizar última conexión (llamar desde el frontend)
CREATE OR REPLACE FUNCTION public.update_last_seen()
RETURNS void AS $$
BEGIN
  UPDATE public.usuarios 
  SET ultima_conexion = NOW() 
  WHERE id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
